from django.db import models
from django.core import validators

class Evaluator(models.Model):
	# not defined the id field as it will be auto generated by django
	name = models.CharField(max_length = 50)
	email = models.CharField(max_length = 50)
	telephone = models.IntegerField()
	address = models.CharField(max_length = 200)

class Report(models.Model):
	evaluator_id = models.ForeignKey(Evaluator, on_delete=models.CASCADE)
	property_address = models.CharField(max_length = 200)
	market_value = models.DecimalField(max_digits=200, decimal_places=7, null=True, blank=True)
	EXTENSIONS = [validators.FileExtensionValidator(allowed_extensions=['pdf'])]
	report = models.FileField(upload_to='files/', validators=EXTENSIONS, blank=True, null=True)
	VALID_STATUSES = (
		('Completed', 'Completed'),
		('Requested', 'Requested'),
	)
	status = models.CharField(choices=VALID_STATUSES, max_length=50, default='Requested')

class User(models.Model):
	name = models.CharField(max_length = 50)
	email = models.CharField(max_length = 50)
	telephone = models.IntegerField()
	address = models.CharField(max_length = 200)


