from django.db import models
from django.contrib.postgres.fields import JSONField
from django.core import validators

EXTENSIONS = [validators.FileExtensionValidator(allowed_extensions=['pdf','jpg'])]

#class SiteAdmin(models.Model):
#	payment_info_id = models.ForeignKey(PaymentInfo, on_delete=models.CASCADE, null=True)    

class PaymentInfo(models.Model):
	account_number = models.IntegerField()
	bank_name = models.CharField(max_length=200)
	bank_branch = models.CharField(max_length=200)
	ifsc_code = models.CharField(max_length=11)

class Evaluator(models.Model):
	# not defined the id field as it will be auto generated by django
	name = models.CharField(max_length=200)
	email = models.CharField(max_length=200)
	phone = models.IntegerField(null=True)
	company_name = models.CharField(max_length=200, null=True)
	company_address = models.CharField(max_length=200, null=True)
	aadhaar_number = models.IntegerField(null=True)
	pan = models.IntegerField(null=True)
	cin = models.IntegerField(null=True)
	supporting_docs = models.FileField(upload_to='supporting_docs/', validators=EXTENSIONS, blank=True, null=True)
	payment_info = models.ForeignKey(PaymentInfo, on_delete=models.CASCADE, null=True)
	VALID_STATUSES = (
		('Inactive', 'Inactive'),
		('Registration-in-progress', 'Registration-in-progress'),
		('Registered', 'Registered'),
		('Rejected', 'Rejected')
	)
	status = models.CharField(choices=VALID_STATUSES, max_length=200, default='Inactive', null=True)

class Property(models.Model):
	type = models.CharField(max_length=200)
	name = models.CharField(max_length=200)
	number = models.CharField(max_length=10)
	floor = models.CharField(max_length=50)
	street = models.CharField(max_length=200)
	locality = models.CharField(max_length=200)
	city = models.CharField(max_length=200)
	pincode = models.CharField(max_length=200)
	age = models.CharField(max_length=200)
	sqft = models.CharField(max_length=200)

class Report(models.Model):
	evaluator = models.ForeignKey(Evaluator, on_delete=models.CASCADE)
	property = models.ForeignKey(Property, on_delete=models.CASCADE, null=True)
	report_json = JSONField(null=True, blank=True)
	report_field_extensions_json =JSONField(null=True, blank=True)
	report_annexure = models.FileField(upload_to='report_annexure/', validators=EXTENSIONS, blank=True, null=True)

	
class User(models.Model):
	name = models.CharField(max_length = 200)
	email = models.CharField(max_length = 200)
	phone = models.IntegerField(null=True)
	company_name = models.CharField(max_length=200, null=True)
	location = models.CharField(max_length = 200, null=True)

class ReportRequest(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	report = models.ForeignKey(Report, on_delete=models.CASCADE, null=True, blank=True)
	payment_reference_number = models.CharField(max_length=200, null=True, blank=True)
	ALLOWED_STATES_FOR_USER = (
		('Requested', 'Requested'),
		('Quote Received', 'Quote Received'),
		('Payment Sent', 'Payment Sent'),
	)
	ALLOWED_STATES_FOR_EVALUATOR = (
		('Payment Recieved', 'Payment Recieved'),
		('Ready to Download Report', 'Ready to Download Report'),
		('Completed', 'Completed')
	)
	VALID_STATUSES = ALLOWED_STATES_FOR_USER + ALLOWED_STATES_FOR_EVALUATOR
	status = models.CharField(choices=VALID_STATUSES, max_length=200, default='Requested')


